language: python
services: docker

jobs:
  include:
  - name: Python 3.8.0 on Xenial Linux
    os: linux
    python: 3.8
  - name: Python 3.7.4 on macOS
    os: osx
    language: shell
    osx_image: xcode11.2
  - name: Python 3.8.0 on Windows
    os: windows
    language: shell
    before_install:
    - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat"
      amd64'
    - choco install python --version 3.8.0
    - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"

env:
  global:
  - CIBW_BUILD=cp3?-*
  - CIBW_SKIP="*-win32 *-manylinux_i686"
  - CIBW_MANYLINUX_X86_64_IMAGE=dockcross/manylinux2014-x64
  - CIBW_TEST_REQUIRES="pytest"
  - CIBW_TEST_COMMAND="python -m pytest --pyargs qdldl"
  - CIBW_BEFORE_BUILD="python -m pip install cython"
  - TWINE_USERNAME=bstellato
  # TWINE_PASSWORD
  - secure: jEzPfPAADi4vT4L8KO4Ht5sDMhJoJY+is2SgCTCDv6FMz8+Cq7BbkvtWp7iTrBbGn4lB668bGRztA+m1VhJszRNQGa7vFgauxTnZ0NTOwBIdH36E9PUZSai7WPmEdcpJcpVE2XeV1RcT7zBBzGmMM3QqG1W0FSZkiJNYe4Wwu0Kh+8/5hT6aesqAGix+f1tX8BEXq0Ad9a6SZwvAvLO7SjpXZ35QB6YaI0p72dY0j0sKG7O5FLBuXcrN37+JiD4THHBXcjv1aqhrywzT/9Zmgt/dbnywI+E33U7k1vCbKDHojTT85rwJP9tAi1Pzmg5vakG6Z8ca3ZOryKS6G7QBPLVKHpUpw8VhOB8o8SRujegCepANWuECGjB52um8P013tUiOWHv3PRU4vyfUtmmcDUimL8zYwufwwufLyvbcBkKveyvh806mrZE7LVMtAtIFq2D5VPeA8dyKYWas5z65v2aRS0qsLgJyLrNhbF14qPe6tsM9fhA6r1hpYuhhiRts3GCA2FRBEIe96DSQgNS4nBMaoMHxVTCs28NcI0hjDgXTMGBoX9ONe38tL0HkP/y/76CurAMojz6K9KUZlSClATlnUKDAifyQ20w4950TavivxiumSsoy5ky7k73FHqqtLy6a+O0JBNNYRIdvRYBGoXRwTby3JLZOQZ186O8Cctc=

install:
- python -m pip install twine cibuildwheel==1.1.0

script:
- python -m cibuildwheel --output-dir wheelhouse

after_success:
- if [[ $TRAVIS_TAG ]]; then python -m twine upload wheelhouse/*.whl; fi
