language: python

services: docker

jobs:
  include:
    # perform a linux build
    - name: "Python 3.8.0 on Xenial Linux"
      os: linux
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    # and a mac build
    - name: "Python 3.7.4 on macOS"
      os: osx
      language: shell
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
    # and a windows build
    - name: "Python 3.8.0 on Windows"
      os: windows
      language: shell
      before_install:
        - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        # - choco install visualstudio2019buildtools --package-parameters "--includeRecommended --includeOptional"
        # - choco install visualstudio2019-workload-vctools

# NBVV<
# 'python' points to Python 2.7 on macOS but points to Python 3.8 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
# TODO: CONTINUE FROM HERE!


env:
  global:
    # Only build on Python 3 and skip 32-bit builds
    - CIBW_BUILD=cp3?-*
    - CIBW_SKIP="*-win32 *-manylinux_i686"
    # build using a different image from the docker registry
    - CIBW_MANYLINUX_X86_64_IMAGE=dockcross/manylinux2014-x64
    # - CIBW_MANYLINUX_I686_IMAGE=dockcross/manylinux-x86
    - CIBW_TEST_REQUIRES="pytest"
    - CIBW_TEST_COMMAND="python -m pytest --pyargs qdldl"
    - CIBW_BEFORE_BUILD="python -m pip install cython"
    - TWINE_USERNAME=bstellato
      # Note: TWINE_PASSWORD is set in Travis settings

install:
  - python -m pip install twine cibuildwheel==1.1.0

script:
  # build the wheels, put them into './wheelhouse'
  - python -m cibuildwheel --output-dir wheelhouse

after_success:
  # if the release was tagged, upload them to PyPI
  - if [[ $TRAVIS_TAG ]]; then python -m twine upload wheelhouse/*.whl; fi
