language: python

jobs:
  include:
    # perform a linux build
    - services: docker
    # and a mac build
    - os: osx
      language: shell
    # and a windows build
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"

env:
  global:
    - CIBW_SKIP="cp27-*"
    - CIBW_TEST_REQUIRES="pytest"
    - CIBW_TEST_COMMAND="cd {project} && python -m pytest module/tests"
    # Install cmake
    - CIBW_BEFORE_BUILD_LINUX="pip install cmake; rm `python -c 'import sys; print(sys.executable[:-6])'`cmake; ln -sf `python -c \"from distutils.sysconfig import get_python_lib; print(get_python_lib())\"`/cmake/data/bin/cmake /usr/local/bin/cmake"
    # - CIBW_BEFORE_BUILD_MACOS="brew install cmake"
    - CIBW_BEFORE_BUILD_WINDOWS="choco install cmake & pip install cython"
    - TWINE_USERNAME=bstellato
      # Note: TWINE_PASSWORD is set in Travis settings

install:
  - python -m pip install twine cibuildwheel==1.1.0

script:
  # build the wheels, put them into './wheelhouse'
  - python -m cibuildwheel --output-dir wheelhouse

after_success:
  # if the release was tagged, upload them to PyPI
  - if [[ $TRAVIS_TAG ]]; then python -m twine upload wheelhouse/*.whl; fi
