name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
    env:
      CIBW_BUILD: cp3?-*
      CIBW_SKIP: *-win32 *-manylinux_i686
      CIBW_MANYLINUX_X86_64_IMAGE: dockcross/manylinux2014-x64
      CIBW_TEST_REQUIRES: pytest
      CIBW_TEST_COMMAND: python -m pytest --pyargs qdldl
      CIBW_BEFORE_BUILD: python -m pip install cython

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.7'

    - name: Install cibuildwheel
      run: |
        python -m pip install twine cibuildwheel==1.3.0

    - name: Build wheel
      run: |
        python -m cibuildwheel --output-dir wheelhouse

    - name: Upload artifact
        on:
          push:
            tags:
              - v*
        run: |
          python -m twine upload wheelhouse/*.whl

